#
# for install see: https://docs.docker.com/engine/install/ubuntu/
#

- name: "docker_install"
  hosts: localhost
  become: true
  gather_facts: no

  tasks:

    - name: docker_dependencies
      apt:
        name: "{{ item }}"
        state: latest
      loop: [ "ca-certificates", "curl", "gnupg", "lsb-release" ]

    - name: docker_cert_dir
      file:
        path: /etc/apt/keyrings
        state: directory
        owner: root
        group: root

    - name: remove_docker_cert
      file:
        path: /etc/apt/keyrings/docker.gpg
        state: absent

    - name: get_docker_cert
      shell:
        cmd: |
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg	

    - name: setup_docker_repo
      shell:
        cmd: |
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"\
            | sudo tee /etc/apt/sources.list.d/docker.list

    - name: apt_update
      apt:
        update_cache: true

    - name: install_docker
      apt:
        name: "{{ item }}"
        state: latest
      loop: [ "docker-ce", "docker-ce-cli", "containerd.io", "docker-compose-plugin"]

    - name: confirm_docker_enabled
      systemd:
        name: docker
        state: started
        enabled: yes
        daemon_reload: yes
        


